Update run-sfdx-scanner.yml

diff --git a/.github/workflows/run-sfdx-scanner.yml b/.github/workflows/run-sfdx-scanner.yml
--- a/.github/workflows/run-sfdx-scanner.yml
+++ b/.github/workflows/run-sfdx-scanner.yml
@@ -111,12 +111,20 @@ jobs:
           results-artifact-name: salesforce-code-analyzer-results
           github-token: ${{ github.token }}
 
-      # - name: Run Graph Engine safely
-      #   if: ${{ env.CHANGED_FILES != '' }}
-      #   run: |
-      #     echo "Running Graph Engine..."
-      #     sf code-analyzer run --target ${{ env.CHANGED_FILES }} --rule-selector sfge --view detail --output-file sfge_results.html || true
-      #     echo "SFGE finished (errors may exist in sfge_results.html)"
+      - name: Run Graph Engine safely
+        if: ${{ env.CHANGED_FILES != '' }}
+        run: |
+          echo "Running Graph Engine..."
+          sf code-analyzer run --target ${{ env.CHANGED_FILES }} --rule-selector sfge --view detail --output-file sfge_results.html || true
+          echo "SFGE finished (errors may exist in sfge_results.html)"
           
       
-      
+        # -------------------------------
+        # Upload SFGE Report as Artifact
+        # -------------------------------
+      - name: Upload SFGE results
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: sfge-results
+          path: sfge_results.html
