Update run-sfdx-scanner.yml

diff --git a/.github/workflows/run-sfdx-scanner.yml b/.github/workflows/run-sfdx-scanner.yml
--- a/.github/workflows/run-sfdx-scanner.yml
+++ b/.github/workflows/run-sfdx-scanner.yml
@@ -94,21 +94,13 @@ jobs:
           echo "$FINAL_FILES"
       
           echo "FILES=$FINAL_FILES" >> $GITHUB_ENV
-      # -------------------------------
-      # Guard: Skip SFCA if no changed files remain
-      # -------------------------------
-      - name: Guard against unchanged / excluded files
-        run: |
-          if [ -z "${FILES// }" ]; then
-            echo "No changed files to analyze after exclusions."
-            echo "Skipping Salesforce Code Analyzer to avoid full repository scan."
-            exit 0
-          fi
+
       
       # -------------------------------
       # Run Salesforce Code Analyzer
       # -------------------------------
       - name: Run Salesforce Code Analyzer (changed files only)
+        id: run-code-analyzer 
         uses: forcedotcom/run-code-analyzer@v2
         with:
           run-arguments: >
@@ -117,3 +109,13 @@ jobs:
             --output-file sfca_results.html
           results-artifact-name: salesforce-code-analyzer-results
           github-token: ${{ github.token }}
+
+          
+      # -------------------------------
+      # Fail on Sev 1 / Sev 2 (changed files only)
+      # -------------------------------
+      - name: Fail on Critical/High Violations (Changed Files Only)
+        if: |
+          steps.run-code-analyzer.outputs.num-sev1-violations-in-changed-files > 0 ||
+          steps.run-code-analyzer.outputs.num-sev2-violations-in-changed-files > 0
+        run: exit 1
